/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children, pagina, guitarra }) => {
   return (
      <div>
         <Head>
            <title>GuitarLA - {pagina}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            {/* // eslint-disable-next-line @next/next/no-page-custom-font */}
            <link
               href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;300;400;500;600;700;800;900&display=swap"
               rel="stylesheet"
            />
         </Head>

         <Header guitarra={guitarra} />

         {children}

         <Footer />
      </div>
   );
};

Layout.defaultProps = {
   guitarra: null,
};

export default Layout;
